[versions]
kotlin = "2.3.10"
ktlint = "14.0.1"
kover = "0.9.6"

[libraries]
# Add your dependencies here

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
